2023-11-24 21:19:24,381 [INFO] basefile.py:18 found element for locator: ('xpath', "//h1[@align='center']")
2023-11-24 21:19:59,907 [WARNING] connectionpool.py:872 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000297531177A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a5379dc5-91e6-4816-80c3-3355ce838b85/window
2023-11-24 21:20:04,005 [WARNING] connectionpool.py:872 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029753114FB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a5379dc5-91e6-4816-80c3-3355ce838b85/window
2023-11-24 21:20:08,100 [WARNING] connectionpool.py:872 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029753114FE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a5379dc5-91e6-4816-80c3-3355ce838b85/window
